### ISSUE TITLE
Error in bash

### ISSUE THREAD

**Issue by jokerigno** [IVData/dockerfiles#1] opened 2017-12-29 19:08 UTC
Hi IVData,

I just installed your fantastic docker solution. It works but in bash I see the following error:

$sudo docker exec -t -i mopidymultiroom_mopidy_1 bash
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "process_linux.go:87: adding pid 22208 to cgroups caused \"failed to write 22208 to cgroup.procs: write /sys/fs/cgroup/systemd/docker/64a4a5899f469666ad43865f87a5c061eaafbc2860567c5fcd76e2525ed86858/cgroup.procs: no space left on device\""

Can you please help me?

Moreover can you please suggest me how to install different interfaces? I love Iris and I would love to add it.

Thank you in advance!

**Comment by hamishfagg** [comment] 2017-12-31 21:41
Hi there,

Thanks for reporting issues here - you might be the first one to actually try using this =P

The bit at the end of your error "no space left on device" suggests to me you might be low on space either on your host machine or in your docker. If you have plenty of space I'd suggest trying to update docker and everything else on your PC.

As for adding Iris, I'll look into how I can allow people to add mopidy extensions. Otherwise I can just add it to the dockerfile.

**Comment by jokerigno** [comment] 2018-01-02 17:52
That's the first thing I tried (rebooting and searching for updates ).

Nothing changed.

My Synology Nas (running docker) has a lot of space so I'm sure is not related.

Maybe I can increase docker image volume (I'll Google it) and see if something changes.

Thank you

**Comment by hamishfagg** [comment] 2018-01-02 20:35
Yeah I tried looking up your error and got nothing =\

Just wondering, are you trying to run bash to install Iris? Because if I can add it to the image that will sort of solve your problem =) but I will try to reproduce your issue here in the meantime.

Another question: what arch is your Synology? (x86, armhf, etc).

**Comment by jokerigno** [comment] 2018-01-02 21:53
Yes! I tried to run bash just to install mopidy-iris and I found out the error. 

Until today I ran other images made by those great guys at linuxserver.io without issue. Can I be releated  to the image used?

Thank you!

**Comment by jokerigno** [comment] 2018-01-02 23:15
Ah I forgotten the last question. 

I run xpenology (DSM synology OS on a dell t20 with intel Xeon.

**Comment by hamishfagg** [comment] 2018-01-03 06:29
Unfortunately I can't reproduce this on my end =\ which makes things difficult.

On the topic of extensions, should I make a script for startup of the container, that checks an ENV var for extensions to install?

**Comment by jokerigno** [comment] 2018-01-03 07:02
That would be great!

It will allow me to install a different frontend and also other components (like mopidy-synology) so I will be able to have everything I need!

**Comment by hamishfagg** [comment] 2018-01-04 19:29
I will start working on this, but it might not be done till next week as I have a lot on at the moment.

Thanks for your feedback though - I haven't really had the chance to properly use all of this stuff outside testing it, so it's great to get an idea of how it works in practice.

**Comment by jokerigno** [comment] 2018-01-05 10:23
Great!

It would be awesome if you'll help to use this docker compose to have my personal multiroom system (mopidy + snapcast server running on NAS) and snapcast clients running on other devices!

Thank you!

**Comment by hamishfagg** [comment] 2018-01-10 18:45
Hey I'm back.  
So I have added a small check when the container is run, that calls:  
`pip install $MOPIDY_PACKAGES`  
IF that environment variable exists. So you should be able to add mopidy-iris or any space-delimited list of packages you want, so long as they exist in pip.

Please test and let me know if it works for you, and I will update the readme.

(I haven't got the ARM image to build yet, but it should still work for you if you update from dockerhub).

**Comment by hamishfagg** [comment] 2018-01-14 20:13
Thinking about it now, I may create another option that prompts the container to upgrade mopidy and all of the pip packages - since I can see a number of those extensions/mopidy itself being updated with new features etc, and it'd be annoying to have to get the container rebuilt for that.

**Comment by jokerigno** [comment] 2018-01-16 20:32
OK I tried. The pip install is not enough for all the extension, for example mopidy-spotify which needs apt-get to install all dependencies.
Using prompt I managed to make it works :)

Thank you!

Regarding update it will be great to have the change to maintain the mopidy packages up to date!

**Comment by hamishfagg** [comment] 2018-01-16 20:58
Alright thanks for letting me know. I might add APT_PACKAGES and PIP_PACKAGES.
I'm basically just making a generic ubuntu image now =P

**Comment by hamishfagg** [comment] 2018-01-31 21:50
Closing as APT_PACKAGES and PIP_PACKAGES have been added. If you have any problems using these vars please open another issue.

**Closed as completed by hamishfagg** 2018-01-31 21:50 UTC

**Comment by hamishfagg** [comment] 2018-02-08 19:55
Hey again. Just commenting to let you know, because github doesn't do PMs apparently.
I've added some default packages back into the mopidy images. GMusic, Spotify, TuneIn, Moped, and Party UI should be included now. It'd be awesome if you could make sure the spotify one works at least since I don't have an account =)

**Comment by jokerigno** [comment] 2018-02-09 20:43
Hey!

I duplicated my working mopidy docker and added new variables as you can see below:
![image](https://user-images.githubusercontent.com/23552762/36049188-3066b606-0de2-11e8-90d3-b5bdfbc1867f.png)

But nothing changed. I have done something wrong?

**Comment by hamishfagg** [comment] 2018-02-09 21:11
You might want to remove your apt-packages var since spotify should be included (but I used the pip package, so installing on apt might break it).
Can you check the log to see if there is any spotify-related errors from mopidy?

**Comment by jokerigno** [comment] 2018-02-09 22:41
Done.

Nothing changed...and there's nothing spotify oriented. Also the Iris frontend is missing:


```
018-02-09 22:39:50 | stdout | [37mINFO     Starting GLib mainloop[0m
-- | -- | --
2018-02-09 22:39:50 | stdout | [37mINFO     HTTP server running at [::]:6680[0m
2018-02-09 22:39:50 | stdout | [37mINFO     MPD server running at [::]:6600[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Audio output set to "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo"[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Starting Mopidy core[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Creating dir /root/.local/share/mopidy/m3u[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Starting Mopidy audio[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Starting Mopidy mixer: SoftwareMixer[0m
2018-02-09 22:39:50 | stdout | [33mWARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.[0m
2018-02-09 22:39:50 | stdout | [33mWARNING    scrobbler/password must be set.[0m
2018-02-09 22:39:50 | stdout | [33mWARNING    scrobbler/username must be set.[0m
2018-02-09 22:39:50 | stdout | [33mWARNING  Found scrobbler configuration errors, the extension has been automatically disabled:[0m
2018-02-09 22:39:50 | stdout | [33mWARNING    local/media_dir must be set.[0m
2018-02-09 22:39:50 | stdout | [33mWARNING    local/media_dirs unknown config key. Did you mean media_dir?[0m
2018-02-09 22:39:50 | stdout | [33mWARNING  Found local configuration errors, the extension has been automatically disabled:[0m
2018-02-09 22:39:50 | stdout | [33mWARNING    gmusic/password must be set.[0m
2018-02-09 22:39:50 | stdout | [33mWARNING    gmusic/username must be set.[0m
2018-02-09 22:39:50 | stdout | [33mWARNING  Found gmusic configuration errors, the extension has been automatically disabled:[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Disabled extensions: gmusic, local, scrobbler[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Enabled extensions: mpd, http, file, stream, m3u, softwaremixer, moped, party[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Creating dir /root/.local/share/mopidy[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Creating dir /root/.cache/mopidy[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Loading config from command line options[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Loading config from /root/.config/mopidy/mopidy.conf[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Loading config from builtin defaults[0m
2018-02-09 22:39:50 | stdout | [37mINFO     Starting Mopidy 2.0.1[0m

```

**Comment by hamishfagg** [comment] 2018-02-09 23:43
Hmm weird. That seems like an old version of the container, because it no longer contains scrobbler. I'll check I haven't accidentally pushed an old build

**Comment by hamishfagg** [comment] 2018-02-10 20:27
Pull the image again now and give it a go.

**Comment by jokerigno** [comment] 2018-02-11 22:53
It works like a charm! I tested spotify both on iris and material web interfaces :)

**Comment by jokerigno** [comment] 2018-02-17 11:48
Hey, It's always me. 

I tried also to implement snapcast client but it doesn't work.

This is the error 

[Err] Exception in Controller::worker(): resolve: Host not found (authoritative)

Please notice that I tried to run it as root in order to give access to my usb external soundcard mounted in my synology nas.

Thank you in advance! :)

**Comment by hamishfagg** [comment] 2018-02-18 23:55
I'm always happy to have stuff actually tested in the real world =)

I can only think that I've named the stream "Snapserver" and the client is looking for "snapserver"

Can you try running the server with env var 'stream_name' set to 'snapserver'?

**Comment by hamishfagg** [comment] 2018-02-19 23:43
Hi again. For some reason I had updated the arm image for snapclient and not the x64 one.

Can you please update your snapserver and snapclient images. Then you'll just need to supply the HOST env var to the client (the value should be the IP or hostname of the snapserver).
