### ISSUE TITLE
install DLNA Renderer ?

### ISSUE THREAD

**Issue by Kollisionskurs** [IVData/dockerfiles#16] opened 2021-01-13 06:44 UTC
Hi,
first of all thanks for the images !! I'm a docker Newbie and I need a tip. 
I want to install a dlna renderer - so i can stream music from my smartphone to mopidy ... how can I do that ? 

my Stack:

version: "2.1"
services:
  mopidy:
    image: ivdata/mopidy:latest
    container_name: mopidy
    hostname: mopidy
    volumes:
    - /srv/dev-disk-by-label-cfusb/docker/mopidy/snapserver/fifo:/tmp/snapcast
    - /srv/dev-disk-by-label-cfusb/docker/mopidy/music:/media/music
    - /srv/dev-disk-by-label-cfusb/docker/mopidy:/mopidy
    environment: 
    # - APT_PACKAGES='upmpdcli'
    - PIP_PACKAGES='Mopidy-dLeyna'
    ports:
    - "6680:6680"
    - "6600:6600"
  snapserver:
    image: ivdata/snapserver:latest
    container_name: snapserver
    hostname: snapserver
    volumes:
    - /srv/dev-disk-by-label-cfusb/docker/mopidy/snapserver/fifo:/tmp/snapcast/
    ports:
    - "1704:1704"
    - "1705:1705"
    - "1780:1780"
    restart: unless-stopped

thanks

**Comment by spiro-c** [comment] 2021-01-18 04:50
You can install like this but Mopidy-dLeyna or other extension but, Mopidy-dLeyna will not work it missing some other packages in the docker image 
`libdbus-glib-1-dev
dleyna-server
dbus-python`
and plus u need to pass host network to docker
```
mopidy:
    image: "ivdata/mopidy"
    ports:
        - "6680:6680"
        - "6600:6600"
    environment:
        - PIP_PACKAGES=Mopidy-dLeyna Mopidy-YouTube
       # - UPDATE=1
    volumes:
        - fifo:/tmp/snapcast/
        - ./music:/media/music
        - ./mopidydata:/mopidy
```
Best option is to rebuild the docker image local on your PC and use that image
```
git clone https://github.com/IVData/dockerfiles.git
cd dockerfiles/mopidy
nano Dockerfile
```
in Dockerfile after line 35 add 
```
    libdbus-glib-1-dev \
    dleyna-server \

``` 
and after line 46 add

```
    Mopidy-dLeyna \
    dbus-python \

```
save the Dockerfile and build your image make sure u copy the last dot on the build command 

```
 docker build --no-cache -t yourimage/mopidy .
```
than in your docker-compose.yml

```
version: '3'

services:
  mopidy:
    image: yourimage/mopidy
    container_name: mopidy
    hostname: mopidy
    network_mode: host
#    environment:
#      - UPDATE=1
    ports:
      - 6680:6680
      - 6600:6600
    volumes:
      - ./fifo:/tmp/snapcast/
      - ./music:/media/music
      - ./mopidydata:/mopidy

```

**Comment by hamishfagg** [comment] 2021-01-18 05:13
@spiro-c thanks for answering this.

You should be able to install the missing apt packages with `APT_PACKAGES` along with Mopidy-dLeyna so that you don't have to rebuild the image.

**Comment by Kollisionskurs** [comment] 2021-01-18 05:52
Thanks for the detailed answer. If there is no other way I will try to build the image myself - especially since I can learn something again in the Docker world. 

@IVData 

Installing the missing apt and pip packages ...

```
- APT_PACKAGES='libdbus-glib-1-dev dleyna-server'                   
- PIP_PACKAGES='Mopidy-dLeyna dbus-python'
```

ends with the following authorization error

> -- INSTALLING APT PACKAGES 'libdbus-glib-1-dev dleyna-server' --
> E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

**Comment by spiro-c** [comment] 2021-01-19 05:07
The problem is container is running under mopidy user and that user don't have access to apt

**Comment by hamishfagg** [comment] 2021-01-31 09:34
I've just merged changes from @spiro-c and rebuilt the containers on dockerhub, so you /should/ be able to do this now. Please let me know.

**Comment by Kollisionskurs** [comment] 2021-01-31 13:12
First of all, I would like to thank you for the implementation - unfortunately the additional features were not installed.
 The following error is in the log:

> **-- INSTALLING APT PACKAGES 'libdbus-glib-1-dev dleyna-server'** --
> Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
> Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
> Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
> Get:4 https://apt.mopidy.com buster InRelease [14.1 kB]
> Get:5 http://deb.debian.org/debian buster/main armhf Packages [7698 kB]
> Get:6 http://security.debian.org/debian-security buster/updates/main armhf Packages [264 kB]
> Get:7 https://apt.mopidy.com buster/contrib Sources [1190 B]
> Get:8 https://apt.mopidy.com buster/main Sources [5778 B]
> Get:9 https://apt.mopidy.com buster/main armhf Packages [3863 B]
> Get:10 https://apt.mopidy.com buster/contrib armhf Packages [1697 B]
> Get:11 https://apt.mopidy.com buster/non-free armhf Packages [719 B]
> Get:12 http://deb.debian.org/debian buster-updates/main armhf Packages [7832 B]
> Fetched 8236 kB in 9s (915 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package 'libdbus-glib-1-dev
> E: Unable to locate package dleyna-server'
> **-- INSTALLING PIP PACKAGES 'Mopidy-dLeyna dbus-python' --**
> Invalid requirement: ''Mopidy-dLeyna'
> Traceback (most recent call last):
>   File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/requirements.py", line 93, in __init__
>     req = REQUIREMENT.parseString(requirement_string)
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1632, in parseString
>     raise exc
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1622, in parseString
>     loc, tokens = self._parse( instring, 0 )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
>     loc,tokens = self.parseImpl( instring, preloc, doActions )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3395, in parseImpl
>     loc, exprtokens = e._parse( instring, loc, doActions )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
>     loc,tokens = self.parseImpl( instring, preloc, doActions )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3717, in parseImpl
>     return self.expr._parse( instring, loc, doActions, callPreParse=False )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
>     loc,tokens = self.parseImpl( instring, preloc, doActions )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3378, in parseImpl
>     loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1383, in _parseNoCache
>     loc,tokens = self.parseImpl( instring, preloc, doActions )
>   File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 2689, in parseImpl
>     raise ParseException(instring, loc, self.errmsg, self)
> pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)During handling of the above exception, another exception occurred:Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line
>     req = Requirement(req)
>   File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/requirements.py", line 97, in __init__
>     requirement_string[e.loc : e.loc + 8], e.msg
> pip._vendor.packaging.requirements.InvalidRequirement: Parse error at ""'Mopidy-"": Expected W:(abcd...)

is it a problem that apt cannot resolve the sources yet?

greatings

**Comment by spiro-c** [comment] 2021-01-31 15:24
in docker-compose u need to have 
```yml
- APT_PACKAGES=libdbus-glib-1-dev dleyna-server                   
- PIP_PACKAGES=Mopidy-dLeyna dbus-python
```

whit out the `'`

u can see from the error it looking for 
``` 
'libdbus-glib-1-dev 
and 
dleyna-server' 
```

**Comment by spiro-c** [comment] 2021-01-31 15:41
@Kollisionskurs  and i just read your first post  dleyna-server wont allow you to stream music to moidy , dleyna-server  lets you browse, search, and stream music from your local UPnP/DLNA compliant media server
if you like to stream music from phone u will need upmpdcli

**Comment by Kollisionskurs** [comment] 2021-02-01 08:20
> 
> 
> in docker-compose u need to have
> 
> ```yaml
> - APT_PACKAGES=libdbus-glib-1-dev dleyna-server                   
> - PIP_PACKAGES=Mopidy-dLeyna dbus-python
> ```
> 
> whit out the `'`
> 
> u can see from the error it looking for
> 
> ```
> 'libdbus-glib-1-dev 
> and 
> dleyna-server' 
> ```

you're right ... shame on me :-]  Without apostrophes it works perfect

**Comment by Kollisionskurs** [comment] 2021-02-01 08:35
> 
> 
> @Kollisionskurs and i just read your first post dleyna-server wont allow you to stream music to moidy , dleyna-server lets you browse, search, and stream music from your local UPnP/DLNA compliant media server
> if you like to stream music from phone u will need upmpdcli

And you are right on this point too - my goal is to stream from my portable devices via DLNA towards Mopidy. So I would have to include upmpdcli - but the operating system cannot find the package because the repo is not known:

https://www.lesbonscomptes.com/upmpdcli/pages/downloads.html

I could test this in advance by logging into the container console and executing the commands. However, I do not have the authorization for the user mopidy or I need the password for this user.

thanks again for the patience with my project ... !!!

**Comment by spiro-c** [comment] 2021-02-01 10:56
i have test Dockerfile for container whit upmpdcli and dleyna-server  but it's little bit all over the place :) i try to optimized more ;)

**Comment by spiro-c** [comment] 2021-02-01 11:07
you can check it here https://github.com/spiro-c/dockerfiles/tree/dev/mopidyupmp but like i sad it's still work in progress

**Comment by hamishfagg** [comment] 2021-04-04 21:02
Closing since it sounds like this is solved.

**Closed as completed** 2021-04-04 21:02 UTC
